package com.arun.tankerapp.core.domain

import android.content.Context
import androidx.core.content.FileProvider
import com.arun.tankerapp.core.data.repository.ApartmentBill
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import javax.inject.Inject

class ReportGenerator @Inject constructor(
    @ApplicationContext private val context: Context
) {

    fun generateTextReport(bills: List<ApartmentBill>, totalTankers: Int): String {
        val sb = StringBuilder()
        sb.append("WATER BILLING REPORT\n")
        sb.append("Cycle Total Tankers: $totalTankers\n")
        sb.append("--------------------------------\n")
        
        val billable = bills.filter { it.billableTankers > 0 }
        if (billable.isEmpty()) {
            sb.append("No billable units this cycle.\n")
        } else {
            billable.forEach { bill ->
                sb.append("Apt ${bill.apartment.number}: ${bill.billableTankers} Tankers")
                if (bill.totalTankersInCycle > bill.billableTankers) {
                    sb.append(" (Vacant: ${bill.totalTankersInCycle - bill.billableTankers})")
                }
                sb.append("\n")
            }
        }
        sb.append("--------------------------------\n")
        sb.append("Generated by TankerApp")
        return sb.toString()
    }

    // CSV Logic - Story 4.2
    fun generateCsvReport(
        bills: List<ApartmentBill>, 
        totalTankers: Int, 
        fromDate: java.time.LocalDate, 
        toDate: java.time.LocalDate
    ): File {
        val file = File(context.cacheDir, "reports/Billing_Report.csv")
        file.parentFile?.mkdirs()
        
        file.printWriter().use { out ->
            // Header
            out.println("Billing Report")
            out.println("From Date,${fromDate}")
            out.println("To Date,${toDate}")
            out.println("")
            out.println("Apartment Number,Billable Tankers,Total Tankers In Cycle")
            
            // Data
            bills.forEach { bill ->
                out.println("${bill.apartment.number},${bill.billableTankers},${bill.totalTankersInCycle}")
            }
            
            // Footer
            out.println(",,")
            out.println("Total Cycle Tankers,,$totalTankers")
        }
        
        return file
    }
    
    fun getUriForFile(file: File): android.net.Uri {
        return FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
    }
}
