package com.arun.tankerapp.core.domain

import android.content.Context
import androidx.core.content.FileProvider
import com.arun.tankerapp.core.data.repository.ApartmentBill
import dagger.hilt.android.qualifiers.ApplicationContext
import java.io.File
import javax.inject.Inject

class ReportGenerator @Inject constructor(
    @ApplicationContext private val context: Context
) {

    fun generateTextReport(bills: List<ApartmentBill>, totalTankers: Int): String {
        val sb = StringBuilder()
        sb.append("WATER BILLING REPORT\n")
        sb.append("Cycle Total Tankers: $totalTankers\n")
        sb.append("--------------------------------\n")
        
        val billable = bills.filter { it.billableTankers > 0 }
        if (billable.isEmpty()) {
            sb.append("No billable units this cycle.\n")
        } else {
            billable.forEach { bill ->
                sb.append("Apt ${bill.apartment.number}: ${bill.billableTankers} Tankers")
                if (bill.totalTankersInCycle > bill.billableTankers) {
                    sb.append(" (Vacant: ${bill.totalTankersInCycle - bill.billableTankers})")
                }
                sb.append("\n")
            }
        }
        sb.append("--------------------------------\n")
        sb.append("Generated by TankerApp")
        return sb.toString()
    }

    // CSV Logic - Story 4.2
    fun generateCsvReport(
        bills: List<ApartmentBill>, 
        totalTankers: Int, 
        fromDate: java.time.LocalDate, 
        toDate: java.time.LocalDate
    ): File {
        val file = File(context.cacheDir, "reports/Billing_Report.csv")
        file.parentFile?.mkdirs()
        
        // Collect dates where tankers were booked (and billed)
        // Union of all dates in dailyBreakdown
        val dates = bills.flatMap { it.dailyBreakdown.keys }.distinct().sorted()

        file.printWriter().use { out ->
            // Header
            out.println("Billing Report")
            out.println("From Date,${fromDate}")
            out.println("To Date,${toDate}")
            out.println("")
            
            // Column Headers
            // Apartment, Total Billable, [Date 1], [Date 2]...
            val dateHeaders = dates.joinToString(",") { it.toString() }
            out.println("Apartment Number,Total Billable ($totalTankers Cycle),${dateHeaders}")
            
            // Data Rows
            bills.forEach { bill ->
                val sb = StringBuilder()
                sb.append(bill.apartment.number).append(",")
                sb.append(bill.billableTankers).append(",")
                
                // Date Columns
                val dateValues = dates.joinToString(",") { date ->
                    (bill.dailyBreakdown[date] ?: 0).toString()
                }
                sb.append(dateValues)
                
                out.println(sb.toString())
            }
            
            // Footer: Daily Totals
            out.println("")
            out.print("Daily Totals,,")
            val dailyTotals = dates.map { date ->
                bills.sumOf { it.dailyBreakdown[date] ?: 0 }
            }
            out.println(dailyTotals.joinToString(","))
        }
        
        return file
    }
    
    fun getUriForFile(file: File): android.net.Uri {
        return FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
    }
}
